source 'https://rubygems.org'

# gem 'jekyll', '3.8.4'
gem 'github-pages', group: :jekyll_plugins

group :jekyll_plugins do
  gem 'jekyll-feed'
  gem 'jekyll-seo-tag'
  gem 'jekyll-sitemap'
  gem "jekyll-remote-theme"
end

gem "webrick", "~> 1.7"
