name: Daily Empty Commit

on:
  schedule:
    - cron: '0 */12 * * *' # Runs at minute 0 past every 12th hour

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Commit and Push
        run: |
          git config user.name "Leandro Pessini"
          git config user.email "leandro@pessini.me"
          git commit --allow-empty -m "Prevent streamlit from going to sleep mode"
          git push origin main 
